### ISSUE TITLE
프로젝트 구조 수정 요청

### ISSUE THREAD

**Issue by zzinpan** [Sehyun-Study/youngmin-rps#1]
<img width="303" alt="image" src="https://github.com/Sehyun-Study/youngmin-rps/assets/9654829/fc3b78eb-1a0c-4fc7-9f81-ecd5d975b3d0">

일반적으로 프로젝트 루트경로에 프로젝트 내용이 보여야합니다.
현재는 rockScissorPaperGame이라는 폴더가 감싸고 있네요.

**Comment by 0minee** [comment]
프로젝트 구조 수정 완료되었습니다
