### ISSUE TITLE
지렁이게임 인터페이스

### ISSUE THREAD

**Issue by 0minee** [Sehyun-Study/youngmin-rps#13]
class interfaceEarthWorm {

    constructor(worm) {  //생성자
      this.worm = worm;
    }

  
    gameStart(){
      //게임 시작시 실행할 함수
    }
  
    getHeadDirection(){
      //지렁이의 머리 방향
    }
  
    randomApple() {
      //사과가 랜덤으로 나오는 함수
    }

    addLength(){
      //사과를 먹었을때 길이 증가
    }
  
    getAppleCoord() {
      //사과의 좌표 구하기
    }
    
    getHeadCoord(){
      //머리 좌표 구하기
    }
  
    getBodyCoord(){
      //몸통 좌표 구하기
    }

    getMapCoord() {
      //맵 전체 좌표 구하기
    }
    
    initMap() {
      //맵 사이즈 설정
    }
  
    gameOver() {
      //게임 종료시 실행되는 함수
    }
  
    moveCheck() {
      //지렁이의 움직임을 지속적으로 체크
    }

  }

**Comment by zzinpan** [comment]
이슈를 잘못생성하셨어요.
관련 저장소에 이슈를 다시 생성해주세요.
이슈 클로즈합니다.
