### ISSUE TITLE
메서드가 넘치는 역할을 갖고 있습니다.

### ISSUE THREAD

**Issue by zzinpan** [Sehyun-Study/youngmin-rps#2]
https://github.com/Sehyun-Study/youngmin-rps/blob/dcc6a88198d54f6fd9f868d9d8b31e78e67bced3/rockScissorPaperGame/src/GameUtil/Player.java#L51-L69

이 메서드를 호출하면, 게임이 실행될거라는 예측을 할 수 없었어요.
객체지향 설계 SOLID의 단일책임의 원칙을 찾아보고 그 것이 뭔지 답변해주세요.

**Comment by 0minee** [comment]
*SOLID 원칙이란
-SRP(Single Responsibility Principle) 단일책임원칙 : 클래스는 하나의 책임(기능)만 가져야 한다.
-OCP(Open Closed Priciple) 개방 폐쇄 원칙: 확장에는 열려 있어야 하며 수정에는 닫혀 있어야 한다.
-LSP(Listov Substitution Priciple) 리스코프 치환 원칙 : 부모객체를 호출할 때 자식객체가 부모객체를 대체할 수 있어야 한다(다형성 원리)
-ISP (Interface Segregation Principle) 인터페이스 분리 원칙 : 인터페이스는 각 기능의 사용에 맞게 분리해야 한다
-DIP (Dependency Inversion Principle) 의존역전원칙 : 어떤 클래스를 참조해야 한다면 클래스의 상위 요소를 참조해야 한다. (구현 클래스가 아닌 인터페이스(불변)를 보라는 뜻)

**Comment by zzinpan** [comment]
네 SOLID는 객체 설계 관점이지만,
단일책임은 기능에서도 마찬가지로 적용되는 개념이라고 봐요.

반영 확인되어 이슈 클로즈합니다.
