### ISSUE TITLE
Player 클래스는 Utility 인가요?

### ISSUE THREAD

**Issue by zzinpan** [Sehyun-Study/youngmin-rps#3]
`Player` 클래스는 유틸리티 패키지에 포함되어 있습니다.
프로그래밍에서 유틸리티는 어떤 의미를 갖는지 답글로 달아주세요.

**Comment by 0minee** [comment]
<프로그래밍에서의 Utility>
* 보통 Utility 라는 이름은 개발자의 편의를 위해 특정 목적을 가진 여러 메서드를 제공하는 묶음에 사용한다.
* 가장 중요한 특징은 특정 작업을 수행하는 로직을 캡슐화하고, 다양한 곳에서 제약 없이 재사용 가능하도록 설계되어야 한다.
* 인스턴스를 생성하지 않고 직접 메서드를 호출할 수 있어야 한다. (static 메서드)

>>따라서 가위바위보 게임의 플레이어에 관련된 class는 Utility보다는 
해당 게임을 구성하는 요소를 기능단위로 분리한 Module로 보는것이 더 적합하다.

**Comment by 0minee** [comment]
<프로그래밍에서의 Utility>
* 보통 Utility 라는 이름은 개발자의 편의를 위해 특정 목적을 가진 여러 메서드를 제공할때 사용한다.
* 가장 중요한 특징은 특정 작업을 수행하는 로직을 캡슐화하고, 다양한 곳에서 제약 없이 재사용 가능하도록 설계되어야 한다.
* 인스턴스를 생성하지 않고 직접 메서드를 호출할 수 있어야 한다. (static 메서드)

>>따라서 가위바위보 게임의 플레이어에 관련된 class는 Utility보다는 
해당 게임을 구성하는 요소를 기능단위로 분리한 Module로 보는것이 더 적합하다.

**Comment by zzinpan** [comment]
👍
