### ISSUE TITLE
다른 인자값을 넘길 수 있습니다.

### ISSUE THREAD

**Issue by zzinpan** [Sehyun-Study/youngmin-rps#5]
https://github.com/Sehyun-Study/youngmin-rps/blob/dcc6a88198d54f6fd9f868d9d8b31e78e67bced3/rockScissorPaperGame/src/GameUtil/Game.java#L10-L17

현재 코드에서는 인자값으로 0만 넘기는 것같아요.
0과 1의 차이가 무슨 의미인지 모르겠습니다.

또한 다른값을 넘겼을 때, 동작이 명확하지 않습니다.
함수의 동작이 누가봐도 명확했으면 좋겠습니다.

**Comment by 0minee** [comment]
검토해본 결과 불필요한 메서드인것 같아 삭제하였습니다.

**Comment by zzinpan** [comment]
확인했습니다.
